### ISSUE TITLE
Checked out repo, initialized submodules has errors.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [sebas77/Svelto.Tasks.Tests#1]
Unity 2020.1.0a16.1913

Most are, assembly with name already exists.

![image](https://user-images.githubusercontent.com/1968109/71301364-096f1c80-2403-11ea-8733-33573ddf1a30.png)

Is there anything else I must do to get this repo to run?

Ideally I'm looking for a "Get started using Svelto.Tasks" so I can download/load files async in a new project.

Does this work with UnityWebRequest?

**Comment by sebas77** [comment]
Hey there, I just checked and in the master branch there is no duplication of Svelto code. Specifically I can see you have Svelto in the plugins folder but, the plugins folder doesn't exists in the master (I just deleted a meta file that was a left over)
